version: '3.6'

services:
  mysql-container:
    image: mysql:latest
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: azerty123456
      MYSQL_DATABASE: aws
      MYSQL_USER: aws
      MYSQL_PASSWORD: azerty123456
    networks:
      - backend

  api:
    restart: always
    depends_on:
      - mysql-container
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend
    links:
      - mysql-container:mysql
    environment:
      rds_hostname: mysql-container
      rds_username: aws
      rds_password: azerty123456
      rds_port: 3306
      rds_db_name: aws

networks:
  backend: